# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: Furprint # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: HaMan's CyberHome # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /dist/favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: ä¸»é¡µ # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: æ–‡ç« 
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: å…¨éƒ¨æ–‡ç« 
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: å½’æ¡£æ–‡ç« 
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: ç”Ÿæ´»æ–‡ç« 
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
        # å­èœå•é¡¹é…ç½®
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: æœ‹å‹
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: Contact
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank # åœ¨æ–°æ ‡ç­¾é¡µæ‰“å¼€
      svg: "material-symbols:attach-email-outline-rounded"

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: HaMan # ç”¨æˆ·å
  site: "https://frosti.saroprock.com" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /dist/profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar: # ä¾§è¾¹æ é…ç½®
    social:
      - href: "https://github.com/HaMan412"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/322071443"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/HaMan575"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://github.com/HaMan412"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/322071443"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/HaMan575"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
